version: '3'
services:

  web:
    image: nginx:1.15.12
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - ${NGINX_PORT}:80

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

  php:
    build:
      context: ./docker/php
    #image: magento/magento-cloud-docker-php:7.2-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www